#!/usr/bin/env python3
"""
Generate After Effects PiPL resource (.r) file from JSON configuration
"""

import json
import sys
import os
from pathlib import Path


def calculate_ae_version(version_dict):
    """Calculate AE version number from version components (matches PF_VERSION macro)"""
    major = int(version_dict.get('major', 0))
    minor = int(version_dict.get('minor', 0))
    patch = int(version_dict.get('patch', 0))
    stage = int(version_dict.get('stage', 0))
    build = int(version_dict.get('build', 0))

    # Bit layout constants copied from AE SDK (PF_Version.h)
    PF_VERS_BUILD_BITS = 0x1FF
    PF_VERS_BUILD_SHIFT = 0
    PF_VERS_STAGE_BITS = 0x3
    PF_VERS_STAGE_SHIFT = 9
    PF_VERS_BUGFIX_BITS = 0xF
    PF_VERS_BUGFIX_SHIFT = 11
    PF_VERS_SUBVERS_BITS = 0xF
    PF_VERS_SUBVERS_SHIFT = 15
    PF_VERS_VERS_BITS = 0x7
    PF_VERS_VERS_SHIFT = 19
    PF_VERS_VERS_HIGH_BITS = 0xF
    PF_VERS_VERS_HIGH_SHIFT = 26
    PF_VERS_VERS_LOW_SHIFT = 3

    vers_high = major >> PF_VERS_VERS_LOW_SHIFT

    version_num = (
        ((vers_high & PF_VERS_VERS_HIGH_BITS) << PF_VERS_VERS_HIGH_SHIFT)
        | ((major & PF_VERS_VERS_BITS) << PF_VERS_VERS_SHIFT)
        | ((minor & PF_VERS_SUBVERS_BITS) << PF_VERS_SUBVERS_SHIFT)
        | ((patch & PF_VERS_BUGFIX_BITS) << PF_VERS_BUGFIX_SHIFT)
        | ((stage & PF_VERS_STAGE_BITS) << PF_VERS_STAGE_SHIFT)
        | ((build & PF_VERS_BUILD_BITS) << PF_VERS_BUILD_SHIFT)
    )

    return version_num


def generate_r_file(config_path, output_path):
    """Generate .r file from JSON configuration"""

    # Load configuration
    with open(config_path, 'r') as f:
        config = json.load(f)

    # Extract values
    name = config['name']
    version = config['version']
    vendor = config['vendor']
    category = config['category']
    description = config.get('description', name)
    ae_match_name = config['ae_match_name']
    support_url = config.get('support_url', 'https://github.com')
    info_flags = int(config.get('ae_info_flags', 0))
    out_flags = int(config.get('ae_out_flags', 0))
    out_flags2 = int(config.get('ae_out_flags2', 0))
    reserved_info = int(config.get('ae_reserved_info', 0))
    entry_point = config.get('entry_point', 'EffectMain')
    entry_point_v2 = config.get('entry_point_v2', 'PluginDataEntryFunction2')

    # Calculate version number
    ae_version = calculate_ae_version(version)

    # Generate .r content
    r_content = f'''// Generated by generate_pipl.py
// DO NOT EDIT MANUALLY

#include "AEConfig.h"
#include "AE_EffectVers.h"

#ifndef AE_OS_WIN
    #include "AE_General.r"
#endif

resource 'PiPL' (16000) {{
    {{
        Kind {{ AEEffect }},
        Name {{ "{name}" }},
        Category {{ "{category}" }},
'''

    # Add platform-specific code entry points
    r_content += '''
        #ifdef AE_OS_WIN
            #ifdef AE_PROC_INTELx64
                CodeWin64X86 {"''' + entry_point + '''"},
            #elif defined(AE_PROC_INTEL)
                CodeWin32X86 {"''' + entry_point + '''"},
            #endif
        #elif defined(AE_OS_MAC)
            #ifdef AE_PROC_INTEL64
                CodeMacIntel64 {"''' + entry_point + '''"},
            #elif defined(AE_PROC_INTELx64)
                CodeMacIntel64 {"''' + entry_point + '''"},
            #else
                CodeMacIntel64 {"''' + entry_point + '''"}, // fallback
            #endif
            #ifdef AE_PROC_ARM64
                CodeMacARM64 {"''' + entry_point + '''"},
            #elif defined(AE_PROC_M1)
                CodeMacARM64 {"''' + entry_point + '''"},
            #else
                CodeMacARM64 {"''' + entry_point + '''"}, // fallback
            #endif
        #endif
'''

    # Add version and flags
    r_content += f'''
        /* Version Info */
        AE_PiPL_Version {{ 2, 0 }},
        AE_Effect_Spec_Version {{ PF_PLUG_IN_VERSION, PF_PLUG_IN_SUBVERS }},
        AE_Effect_Version {{ {ae_version} }}, /* {version['major']}.{version['minor']}.{version['patch']} */

        /* Plugin Info Flags */
        AE_Effect_Info_Flags {{ {info_flags} }},

        /* Global OutFlags */
        AE_Effect_Global_OutFlags {{ {out_flags} }},

        AE_Effect_Global_OutFlags_2 {{ {out_flags2} }},

        /* Match Name - MUST BE UNIQUE */
        AE_Effect_Match_Name {{ "{ae_match_name}" }},

        /* Reserved Info */
        AE_Reserved_Info {{ {reserved_info} }},

        /* Support URL */
        AE_Effect_Support_URL {{ "{support_url}" }}
    }}
}};
'''

    # Add PluginDataEntryFunction2 export for modern AE
    if entry_point_v2:
        r_content += f'''
// Modern entry point for CC 2020+
#ifdef AE_OS_MAC
    #ifdef __LP64__
        resource 'aeg64' (16000, "{name}") {{
            "{entry_point_v2}"
        }};
    #endif
#endif
'''

    # Write to file
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(output_path, 'w') as f:
        f.write(r_content)

    print(f"Generated: {output_path}")


def main():
    if len(sys.argv) != 3:
        print("Usage: generate_pipl.py <config.json> <output.r>")
        sys.exit(1)

    config_path = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.exists(config_path):
        print(f"Error: Config file not found: {config_path}")
        sys.exit(1)

    try:
        generate_r_file(config_path, output_path)
    except Exception as e:
        print(f"Error generating .r file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
